
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - human-net

  app:
    build:
      context: ./backend
    container_name: human-factors-app
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SERVER_PORT: ${SERVER_PORT_API}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      SLACK_REDIRECT_URI: "https://${DNS_DOMAIN}/api/slack/oauth_redirect"
      SLACK_COMPLETION_URL: "https://${DNS_DOMAIN}/api/slack/oauth/completion"
      SLACK_CANCELLATION_URL: "https://${DNS_DOMAIN}/api/slack/oauth/cancellation"
    expose:
      - "${SERVER_PORT_API}"
    env_file:
      - .env
    volumes:
      - slack_installations:/data/slack/installations  
    networks:
      - human-net

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        REACT_APP_API_URL: "https://${DNS_DOMAIN}/api/"
    container_name: frontend-app
    ports:
      - "${APP_PORT}:80"
      - "${SECURE_APP_PORT}:443"
    env_file:
      - .env
    environment:
      - DNS_DOMAIN=${DNS_DOMAIN}
    networks:
      - human-net

volumes:
  mysql_data:
  slack_installations: 

networks:
  human-net:
